# Generated by Django 2.1.10 on 2020-02-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=256)),
                ('publish', models.DateTimeField()),
                ('result', models.TextField()),
                ('openresult', models.TextField()),
                ('showresult', models.TextField()),
            ],
        ),
    ]
